;------------------------------------------------------;;----------------------------------;;
;			prints a	  	       ;;		the		   ;;
;	  	very    cute	kitty	  	       ;;	  comment section	   ;;
;------------------------------------------------------;;----------------------------------;;
						       ;;				   ;;
SECTION .data					       ;;	 proudly written	   ;;
						       ;;	     in nano		   ;;
						       ;;----------------------------------;;
	uwu:	db "      |\      _,,,---,,_", 0       ;;				   ;;
	uwu2:	db "ZZZzz /,`.-'`'    -.  ;-;;,_", 0   ;;	  + ascii kitty		   ;;
	uwu3:	db "     |,4-  ) )-,_. ,\ (  `'-'", 0  ;;	   c-string vars	   ;;
	uwu4:	db "    '---''(_/--'  `-'\_) ", 0      ;;				   ;;
						       ;;----------------------------------;;
SECTION .text					       ;;				   ;;
	global		_main			       ;;	   	 		   ;;
	extern		_puts			       ;;				   ;;
						       ;;----------------------------------;;
	_main:					       ;;				   ;;
		push	rbx			       ;;	  +  push stack		   ;;
		call	_meow			       ;;   + call defined 'method' meow   ;;
		pop	rbx			       ;;         + clean up stack	   ;;
		ret				       ;;	     + return		   ;;
						       ;;----------------------------------;;
	_meow:					       ;;				   ;;
		push	rbx			       ;;				   ;;
		lea	rdi, [rel uwu]  	       ;;       + arg addr to uwu	   ;;
		call	_puts			       ;;      + call puts to print	   ;;
		lea	rdi, [rel uwu2] 	       ;;           + next arg	  	   ;;
		call	_puts			       ;; 	      + print		   ;;
		lea	rdi, [rel uwu3]		       ;;				   ;;
		call	_puts			       ;;				   ;;
		lea	rdi, [rel uwu4]		       ;; 				   ;;
		call	_puts			       ;;				   ;; 
		pop	rbx			       ;;        + clean up stack	   ;;
		ret				       ;;	     + return		   ;;
						       ;;----------------------------------;;
; --------------     end of program    --------------- ;;-------- end of comments ---------;;
