#!/bin/sh

echo
printf "\033[1;33m"
echo '------------+         output          +-------------'
printf "\033[0m"
echo
nasm -f macho64 $1.asm && gcc $1.o -o $1 && chmod +x $1 && ./$1
echo
printf "\033[1;33m"
echo '------------+       -----------       +-------------'
printf "\033[0m"
echo
printf "\033[1;35m"
echo '------------+      assembly code      +-------------'
printf "\033[0m" 
echo
objdump -d $1.o
printf "\033[1;35m"
echo '------------+       -----------       +-------------'
printf "\033[0m"
